export { PolicyEngine, policyEngine } from './engine.js';
export type { WrapToolsContext } from './engine.js';
export { PermissionGrantStore } from './store.js';
export type { DomainHandler, PermissionContext } from './types.js';
export { matchGlob, matchAnyGlob } from './matchers/glob-matcher.js';
export { parseCommand, isDeniedCommand } from './matchers/command-parser.js';
export { extractCommands, extractCommandNames, extractReferencedPaths } from './matchers/bash-ast.js';
export type { CommandNode } from './matchers/bash-ast.js';
export { checkPathBoundaries } from './matchers/boundary-checker.js';
export type { BoundaryCheckResult, BoundaryViolation } from './matchers/boundary-checker.js';
export { normalizeToPattern, matchesPattern, getCommandArity } from './matchers/command-arity.js';
export { fileEditDomain } from './domains/file-edit.js';
export { shellDomain } from './domains/shell.js';
export { externalDirDomain } from './domains/external-dir.js';
export { networkDomain } from './domains/network.js';
export { toolLoopDomain, clearToolLoopHistory } from './domains/tool-loop.js';
export { resolvePermissionPolicy } from './resolve-policy.js';
export { buildPermissionDescription, getRiskLevel } from './descriptions.js';
